language: cpp

services:
 - docker

sudo: false

env:
 - DOCKER=i386/ubuntu
 - 

addons:
  apt_packages:
      - libgmp-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-thread-dev
      - autoconf
      - automake
      - libtool

script: ./.travis-build.sh
